name: todo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  after_layout: ^1.1.1+1
  bot_toast: ^4.0.2
  countdown_widget: ^2.0.0
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  fluro: ^2.0.3
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.2.0
  flutter_mobx: ^2.0.6+1
  get_it: ^7.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  mobx: ^2.0.7
  provider: ^6.0.3
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  json_serializable_mobx: ^0.10.2
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri/calibri-regular.ttf
        - asset: assets/fonts/calibri/calibri-italic.ttf
        - asset: assets/fonts/calibri/calibri-bold.ttf
        - asset: assets/fonts/calibri/calibri-bold-italic.ttf
